poi_types:
  restaurant: [cuisine, price_range, rating]
  museum: [theme, entry_fee, hours]
  park: [size, facilities]

pois:
  - id: 1  
    name: "Aqqu"
    type: restaurant
    x: 100
    y: 200
    cuisine: Kazakh
    price_range: medium
    rating: 10
  - id: 2
    name: "National Art Museum"
    type: museum
    x: 300
    y: 400
    theme: Modern Art
    entry_fee: 15
    hours: "10:00-18:00"
  - id: 3
    name: "Sairan"
    type: park
    x: 500
    y: 600
    size: large
    facilities: ["playground", "lake"]

visitors:
  - name: "Aruzhan Zhanabylova"
    nationality: "Kazakhstan"
    visits:
      - poi_id: 1
        date: "15/09/2025"
        rating: 8
      - poi_id: 2
        date: "16/09/2025"
        rating: 10
  - name: "Eldana Ashirova"
    nationality: "Kazakhstan"
    visits:
      - poi_id: 1
        date: "14/09/2025"
        rating: 7
      - poi_id: 3
        date: "16/09/2025"
        rating: 10